version: '3.2'
services:
  jupyter:
    # image: "tensorflow/tensorflow:2.1.1-jupyter"
    image: "bergloman:ad_examples"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
    volumes:
      - type: bind
        source: ..
        target: /tf/jovyan/work
