version: '3.2'
services:
  jupyter:
    image: "bergloman:ad_examples"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
    volumes:
      - type: bind
        source: ..
        target: /home/jovyan/work
